# Generated by Django 5.1.5 on 2025-02-01 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_data_pedido_pedido_status_pedido_valor_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenspedido',
            old_name='itensPedido_pedido',
            new_name='pedido',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
