# Generated by Django 5.1.5 on 2025-02-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_itenspedido_pedido_itenspedido_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='cliente_pedido',
            new_name='cliente',
        ),
    ]
